apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/wordpress
    server: svc.ocp.mycustomdomain.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-data-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/wordpress
    server: svc.ocp.mycustomdomain.io